wac_quizz:
    resource: "@WACQuizzBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

quizz_show:
    path:     /categorie/{id}
    defaults: { _controller: WACQuizzBundle:Default:quizz_show }

checkChoice:
    path :  /checkChoice
    defaults: { _controller: WACQuizzBundle:Default:checkChoice }

insertQuizz:
    path : /insertQuizz
    defaults: { _controller: WACQuizzBundle:Default:insertQuizz }

removeQuizz:
    path : /removeQuizz
    defaults: { _controller: WACQuizzBundle:Default:removeQuizz }

removeUser:
    path : /removeUser
    defaults: { _controller: WACQuizzBundle:Default:removeUser }